const animeData = [
  {
    id: 1,
    title: "One Piece",
    image:
      "https://cdn.myanimelist.net/images/anime/1244/138851.jpg",
    rating: 9.22,
    year: 1999,
    episodes: 1000,
    status: "Ongoing",
    type: "TV",
    genres: ["Action", "Adventure", "Fantasy"],
  },
  {
    id: 2,
    title: "Naruto",
    image:
      "https://cdn.myanimelist.net/images/anime/13/17405.jpg",
    rating: 8.00,
    year: 2002,
    episodes: 220,
    status: "Completed",
    type: "TV",
    genres: ["Action", "Adventure", "Fantasy"],
  },
  {
    id: 3,
    title: "Naruto: Shippuden",
    image:
      "https://cdn.myanimelist.net/images/anime/5/17407.jpg",
    rating: 8.18,
    year: 2007,
    episodes: 500,
    status: "Completed",
    type: "TV",
    genres: ["Action", "Adventure", "Fantasy"],
  },
  {
    id: 4,
    title: "Attack on Titan",
    image:
      "https://cdn.myanimelist.net/images/anime/10/47347.jpg",
    rating: 8.54,
    year: 2013,
    episodes: 25,
    status: "Completed",
    type: "TV",
    genres: ["Action", "Drama", "Fantasy"],
  },
  {
    id: 5,
    title: "Demon Slayer",
    image:
      "https://cdn.myanimelist.net/images/anime/1286/99889.jpg",
    rating: 8.52,
    year: 2019,
    episodes: 26,
    status: "Completed",
    type: "TV",
    genres: ["Action", "Fantasy"],
  },
  {
    id: 6,
    title: "Jujutsu Kaisen",
    image:
      "https://cdn.myanimelist.net/images/anime/1171/109222.jpg",
    rating: 8.63,
    year: 2020,
    episodes: 24,
    status: "Completed",
    type: "TV",
    genres: ["Action", "Supernatural"],
  },
  {
    id: 7,
    title: "My Hero Academia",
    image:
      "https://cdn.myanimelist.net/images/anime/10/78745.jpg",
    rating: 7.87,
    year: 2016,
    episodes: 13,
    status: "Completed",
    type: "TV",
    genres: ["Action", "Superhero"],
  },
  {
    id: 8,
    title: "Death Note",
    image:
      "https://cdn.myanimelist.net/images/anime/9/9453.jpg",
    rating: 8.62,
    year: 2006,
    episodes: 37,
    status: "Completed",
    type: "TV",
    genres: ["Mystery", "Psychological", "Supernatural"],
  },
  {
    id: 9,
    title: "Fullmetal Alchemist: Brotherhood",
    image:
      "https://cdn.myanimelist.net/images/anime/1223/96541.jpg",
    rating: 9.10,
    year: 2009,
    episodes: 64,
    status: "Completed",
    type: "TV",
    genres: ["Action", "Adventure", "Drama"],
  },
  {
    id: 10,
    title: "Hunter x Hunter",
    image:
      "https://cdn.myanimelist.net/images/anime/1337/99013.jpg",
    rating: 9.04,
    year: 2011,
    episodes: 148,
    status: "Completed",
    type: "TV",
    genres: ["Action", "Adventure", "Fantasy"],
  },
  {
    id: 11,
    title: "Dragon Ball Z",
    image:
      "https://cdn.myanimelist.net/images/anime/1277/142022.jpg",
    rating: 8.17,
    year: 1989,
    episodes: 291,
    status: "Completed",
    type: "TV",
    genres: ["Action", "Adventure", "Comedy"],
  },
  {
    id: 12,
    title: "Bleach",
    image:
      "https://cdn.myanimelist.net/images/anime/3/40451.jpg",
    rating: 8.03,
    year: 2004,
    episodes: 366,
    status: "Completed",
    type: "TV",
    genres: ["Action", "Adventure", "Supernatural"],
  },
  {
    id: 13,
    title: "Tokyo Ghoul",
    image:
      "https://cdn.myanimelist.net/images/anime/1498/134113.jpg",
    rating: 7.79,
    year: 2014,
    episodes: 12,
    status: "Completed",
    type: "TV",
    genres: ["Action", "Fantasy", "Horror"],
  },
  {
    id: 14,
    title: "Chainsaw Man",
    image:
      "https://cdn.myanimelist.net/images/anime/1806/126216.jpg",
    rating: 8.53,
    year: 2022,
    episodes: 12,
    status: "Completed",
    type: "TV",
    genres: ["Action", "Fantasy", "Horror"],
  },
  {
    id: 15,
    title: "One Punch Man",
    image:
      "https://cdn.myanimelist.net/images/anime/12/76049.jpg",
    rating: 8.50,
    year: 2015,
    episodes: 12,
    status: "Completed",
    type: "TV",
    genres: ["Action", "Comedy", "Superhero"],
  },
  {
    id: 16,
    title: "Sword Art Online",
    image:
      "https://cdn.myanimelist.net/images/anime/11/39717.jpg",
    rating: 7.20,
    year: 2012,
    episodes: 25,
    status: "Completed",
    type: "TV",
    genres: ["Action", "Adventure", "Fantasy"],
  },
  {
    id: 17,
    title: "Steins;Gate",
    image:
      "https://cdn.myanimelist.net/images/anime/1935/127974.jpg",
    rating: 9.07,
    year: 2011,
    episodes: 24,
    status: "Completed",
    type: "TV",
    genres: ["Drama", "Sci-Fi", "Thriller"],
  },
  {
    id: 18,
    title: "Vinland Saga",
    image:
      "https://cdn.myanimelist.net/images/anime/1500/103005.jpg",
    rating: 8.80,
    year: 2019,
    episodes: 24,
    status: "Completed",
    type: "TV",
    genres: ["Action", "Adventure", "Drama"],
  },
  {
    id: 19,
    title: "Haikyuu!!",
    image:
      "https://cdn.myanimelist.net/images/anime/7/76014.jpg",
    rating: 8.44,
    year: 2014,
    episodes: 25,
    status: "Completed",
    type: "TV",
    genres: ["Sports", "Comedy", "Drama"],
  },
  {
    id: 20,
    title: "Blue Lock",
    image:
      "https://cdn.myanimelist.net/images/anime/1258/126929.jpg",
    rating: 8.29,
    year: 2022,
    episodes: 24,
    status: "Completed",
    type: "TV",
    genres: ["Sports", "Drama"],
  },
  {
    id: 21,
    title: "Spy x Family",
    image:
      "https://cdn.myanimelist.net/images/anime/1441/122795.jpg",
    rating: 8.50,
    year: 2022,
    episodes: 25,
    status: "Completed",
    type: "TV",
    genres: ["Comedy", "Action", "Family"],
  },
  {
    id: 22,
    title: "Your Name",
    image:
      "https://cdn.myanimelist.net/images/anime/5/87048.jpg",
    rating: 8.83,
    year: 2016,
    episodes: 1,
    status: "Completed",
    type: "Movie",
    genres: ["Romance", "Drama", "Supernatural"],
  },
  {
    id: 23,
    title: "A Silent Voice",
    image:
      "https://cdn.myanimelist.net/images/anime/1122/96435.jpg",
    rating: 8.93,
    year: 2016,
    episodes: 1,
    status: "Completed",
    type: "Movie",
    genres: ["Drama", "Romance", "School"],
  },
  {
    id: 24,
    title: "Demon Slayer: Mugen Train",
    image:
      "https://cdn.myanimelist.net/images/anime/1704/106947.jpg",
    rating: 8.65,
    year: 2020,
    episodes: 1,
    status: "Completed",
    type: "Movie",
    genres: ["Action", "Fantasy"],
  },
  {
    id: 25,
    title: "Dr. Stone",
    image:
      "https://cdn.myanimelist.net/images/anime/1613/102576.jpg",
    rating: 8.28,
    year: 2019,
    episodes: 24,
    status: "Completed",
    type: "TV",
    genres: ["Adventure", "Comedy", "Sci-Fi"],
  },
  {
    id: 26,
    title: "Black Clover",
    image:
      "https://cdn.myanimelist.net/images/anime/2/88336.jpg",
    rating: 8.14,
    year: 2017,
    episodes: 170,
    status: "Completed",
    type: "TV",
    genres: ["Action", "Adventure", "Fantasy"],
  },
  {
    id: 27,
    title: "Mob Psycho 100",
    image:
      "https://cdn.myanimelist.net/images/anime/1918/96303.jpg",
    rating: 8.49,
    year: 2016,
    episodes: 12,
    status: "Completed",
    type: "TV",
    genres: ["Action", "Comedy", "Supernatural"],
  },
  {
    id: 28,
    title: "Re:Zero",
    image:
      "https://cdn.myanimelist.net/images/anime/11/79410.jpg",
    rating: 8.23,
    year: 2016,
    episodes: 25,
    status: "Completed",
    type: "TV",
    genres: ["Fantasy", "Psychological", "Drama"],
  },
  {
    id: 29,
    title: "The Promised Neverland",
    image:
      "https://cdn.myanimelist.net/images/anime/1830/118780.jpg",
    rating: 8.50,
    year: 2019,
    episodes: 12,
    status: "Completed",
    type: "TV",
    genres: ["Mystery", "Thriller", "Horror"],
  },
  {
    id: 30,
    title: "Solo Leveling",
    image:
      "https://cdn.myanimelist.net/images/anime/1801/140786.jpg",
    rating: 8.81,
    year: 2024,
    episodes: 12,
    status: "Completed",
    type: "TV",
    genres: ["Action", "Adventure", "Fantasy"],
  },
];

export default animeData;
